openapi: 3.0.1
info:
  title: "md5"
  version: 0.1.0
servers:
- url: "{server}:{port}/"
  variables:
    server:
      default: http://localhost
    port:
      default: "9091"
paths:
  /md5sum:
    get:
      operationId: getMd5sum
      parameters:
      - name: value
        in: query
        required: true
        schema:
          type: string
      responses:
        "200":
          description: Ok
          content:
            text/plain:
              schema:
                type: string
        "500":
          description: Found unexpected output
          content:
            text/plain:
              schema:
                type: string
components: {}
