openapi: 3.0.1
info:
  title: Greeting9876
  version: 0.1.0
servers:
- url: "{server}:{port}/greeting9876"
  variables:
    server:
      default: http://localhost
    port:
      default: "9876"
paths:
  /hello:
    get:
      summary: A resource for generating greetings
      operationId: getHello
      parameters:
      - name: name
        in: query
        description: the input string name
        required: true
        schema:
          type: string
      responses:
        "200":
          description: Ok
          content:
            text/plain:
              schema:
                type: string
        "500":
          description: Found unexpected output
          content:
            text/plain:
              schema:
                type: string
components: {}
